[package]
name = "studiole_di_macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Derive macros for studiole_di"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.114"
quote = "1.0.43"

[lints]
workspace = true
