[package]
name = "alnwick_services"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
alnwick_core = { path = "../core" }
dirs = { workspace = true }
envy = { workspace = true }
error-stack = { workspace = true }
fast_image_resize = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
lofty = { workspace = true }
reqwest = { workspace = true }
rss = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tracing-test = { workspace = true }

[lints]
workspace = true
