[package]
name = "studiole_di"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A simple dependency injection framework for Rust."

[dependencies]
error-stack = { workspace = true }
studiole_di_macros = { path = "../di-macros" }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
